### ISSUE TITLE
Add comment + reaction fuction

### ISSUE THREAD

**Issue by NishaLab** [hungthanhle/rails_tutorial#3]
Thêm tính năng add reaction cho mỗi post. Bây giờ mình muốn các user có thể react cho các post của nhau.
Tạm thời thì sẽ có Like, Love, Haha, Angry, Care như thằng facebook 
Thêm phần comment cho mỗi post.
Design sẽ giống như facebook. Bên dưới post hiển thị các comment cũ và chỗ nhập comment mới + hiển thị reaction của comment đó.
Mỗi comment cũng có thể được thả reaction.
Trước tiên thì bạn thử design qua cái DB sử dụng để làm 2 ý này cho mình review trước rồi làm nhé

**Comment by hungthanhle** [comment]
Estimate time for this task:
Code: 2 days
Test: 2 days
